feat: added ability to override options via env
sh33dafi/jest-sonar pull request #66
Opened 2023-01-11 14:51 UTC by SveLil

Added the feature to override options via environment variables
Include test

2023-01-25 07:10 UTC, sh33dafi requested changes
Thanks for your PR
Please fix the linting issues and add some documentation to the README explaining you which ENV options can be set, and that they wil overwrite any other options

2023-01-25 08:43 UTC, SveLil commented
Fixed linting and added the environment variables to the config options table

2023-02-28 15:08 UTC, SveLil commented
Any progress?

2023-02-28 15:22 UTC, sh33dafi approved these changes

2023-02-28 15:22 UTC, merged